[NTRN-78] upgrade neutron voting registry to v2
neutron-org/neutron-dao pull request #75
Opened 2023-08-11 12:14 UTC by sotnikov-s

**task:** https://hadronlabs.atlassian.net/browse/NTRN-78

2023-08-29 08:41 UTC, NeverHappened requested changes
All good, see very small changes

2023-09-01 10:38 UTC, NeverHappened approved these changes

2023-09-04 15:06 UTC, pr0n00gler approved these changes

2023-09-05 08:12 UTC, swelf19 approved these changes

2023-09-05 14:06 UTC, merged