[NTRN-127] chore: small improvements
neutron-org/neutron-dao pull request #94
Opened 2023-10-21 05:55 UTC by sotnikov-s

**task:** https://hadronlabs.atlassian.net/browse/NTRN-127

**this PR:**
- adds missing `set_contract_version` for the reserve contract;
- optimises migration params check in `execute_migrate_from_xyk_to_cl`.

D.O.D. 6 from the task has been skipped due to majority is opposed to it.

2023-10-21 05:55 UTC, sotnikov-s commented
https://github.com/neutron-org/neutron-tests/actions/runs/6589360521

2023-10-21 15:31 UTC, pr0n00gler commented
> https://github.com/neutron-org/neutron-tests/actions/runs/6589360521

You use `main` of the integration-tests repo in your test run, but you should use `feat/xyk-to-cl-migration` since you the PR is related to the migration of liquidity

2023-10-24 08:19 UTC, sotnikov-s commented
test run against `feat/xyk-to-cl-migration` branch:
https://github.com/neutron-org/neutron-tests/actions/runs/6614904903

test run against `feat/lockdrop-cl-pools-migration` branch:
https://github.com/neutron-org/neutron-tests/actions/runs/6612057482

2023-10-24 14:27 UTC, pr0n00gler requested changes
It's out of scope, but since you've updated the reserve contract, please add similar `CONTRACT_NAME` and `CONTRACT_VERSION` constants in the distribution contract (and `cw2` methods for setting contract info)

2023-10-24 14:27 UTC, pr0n00gler commented on contracts/tokenomics/reserve/src/contract.rs
> +pub(crate) const CONTRACT_NAME: &str = "crates.io:reserve";
In `Cargo.toml` we have name of the contract equals to `neutron-reserve`. Let's keep things consistent and have the same name here.

2023-10-25 10:31 UTC, sotnikov-s commented
test run against `feat/xyk-to-cl-migration` branch:
https://github.com/neutron-org/neutron-tests/actions/runs/6637554276

test run against `feat/lockdrop-cl-pools-migration` branch:
https://github.com/neutron-org/neutron-tests/actions/runs/6637560757

2023-10-25 10:38 UTC, pr0n00gler requested changes

2023-10-25 10:38 UTC, pr0n00gler commented on contracts/tokenomics/distribution/src/contract.rs
> +    set_contract_version(deps.storage, CONTRACT_NAME, CONTRACT_VERSION)?;
Same method must be called in migrate handler

2023-10-26 06:15 UTC, sotnikov-s commented
reran the above jobs:

test run against `feat/xyk-to-cl-migration` branch:
https://github.com/neutron-org/neutron-tests/actions/runs/6637554276

test run against `feat/lockdrop-cl-pools-migration` branch:
https://github.com/neutron-org/neutron-tests/actions/runs/6637560757

2023-10-26 15:25 UTC, NeverHappened approved these changes
Looks nice!

2023-11-01 09:26 UTC, swelf19 approved these changes

2023-11-01 10:04 UTC, merged